services:
  auth-service:
    build: ./auth-service
    ports:
      - "8002:8002"
    networks:
      - mynet
    volumes:
      - auth_data:/app/data
    environment:
      - SQLITE_PATH=/app/data/db.sqlite3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.services.auth.loadbalancer.server.port=8002"

  dl-api:
    build: ./dl-api
    ports:
      - "8000:8000"
    networks:
      - mynet
    volumes:
      - ./dl-api:/app
    depends_on:
      - auth-service
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dlapi.rule=Host(`dlapi.localhost`)"
      - "traefik.http.services.dlapi.loadbalancer.server.port=8000"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8001:8001"
    networks:
      - mynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.services.api.loadbalancer.server.port=8001"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"

  async-worker:
    build: ./async-worker
    ports:
      - "8003:8003"
    networks:
      - mynet
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynet

  consul:
    image: consul:1.15
    ports:
      - "8500:8500"
    networks:
      - mynet

  traefik:
    image: traefik:v3.0
    container_name: projet_complet_traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - mynet
    depends_on:
      - api-gateway
      - auth-service
      - frontend
      - dl-api

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - mynet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  postgres:
    image: postgres:15
    container_name: projet_complet_postgres
    environment:
      POSTGRES_DB: driver_vigilance
      POSTGRES_USER: driver_user
      POSTGRES_PASSWORD: driver_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U driver_user -d driver_vigilance"]
      interval: 10s
      timeout: 5s
      retries: 5

# دمج المجلدات هنا في قسم واحد
volumes:
  postgres_data:
  auth_data:

networks:
  mynet:
    driver: bridge