server {
    listen 80;
    server_name localhost;

    location /api/health {
        proxy_pass http://dl-api:8000/api/health/;
        proxy_set_header Host $host;
    }

    location /api/predict {
        proxy_pass http://dl-api:8000/api/predict/;
        proxy_set_header Host $host;
    }

    location / {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}