# Generated by Django 6.0.3 on 2026-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
